
(use-modules (stampede))

(define conn (conn-from-params params))
(define plain-query    "SELECT * FROM InventoryItem")
(define param-query    "SELECT * FROM InventoryItem WHERE sku = $1")
(define insert-query   "INSERT INTO InventoryItem VALUES ($1, $2, $3, $4, $5)")
(define insert-params  '("INGR-117" "Wine" "ingredient" "4" "bottles"))
(define delete-query   "DELETE FROM InventoryItem WHERE sku = $1")
(define delete-params  '("INGR-117"))

(when (good-conn? conn)
  (let ((res (get-presult conn insert-query insert-params)))
    (when (good-res? res)
      (display (get-res-mesg res))
      (display "Inserting ")
      (display insert-params)
      (newline)
      (display "Good insert, deleting now\n")
      (get-presult conn delete-query delete-params)
      (display "Deleted\n"))))
